packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  esbuild: false
  sharp: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@scalar/agent-chat@0.12.30'
  - '@scalar/api-client@3.18.0'
  - '@scalar/api-reference-react@0.9.67'
  - '@scalar/api-reference@1.68.0'
  - '@scalar/asyncapi-upgrader@0.1.9'
  - '@scalar/blocks@0.1.16'
  - '@scalar/components@0.29.1'
  - '@scalar/helpers@0.11.3'
  - '@scalar/json-magic@0.13.4'
  - '@scalar/oas-utils@0.19.16'
  - '@scalar/schemas@0.9.0'
  - '@scalar/sidebar@0.11.1'
  - '@scalar/snippetz@0.9.30'
  - '@scalar/types@0.19.0'
  - '@scalar/use-hooks@0.4.11'
  - '@scalar/workspace-store@0.60.0'
  - '@tuwaio/nova-connect@0.6.0'
  - '@tuwaio/nova-core@0.6.0'
  - '@tuwaio/nova-transactions@0.6.0'
  - '@tuwaio/orbit-core@0.3.0'
  - '@tuwaio/orbit-evm@0.3.0'
  - '@tuwaio/orbit-solana@0.3.0'
  - '@tuwaio/pulsar-core@0.7.0'
  - '@tuwaio/pulsar-evm@0.6.0'
  - '@tuwaio/pulsar-react@0.5.0'
  - '@tuwaio/pulsar-solana@0.7.0'
  - '@tuwaio/satellite-core@0.5.0'
  - '@tuwaio/satellite-evm@0.5.0'
  - '@tuwaio/satellite-react@0.5.0'
  - '@tuwaio/satellite-solana@0.5.0'
  - '@tuwaio/siwx-core@0.3.0'
  - '@tuwaio/siwx-evm@0.3.0'
  - '@tuwaio/siwx-react@0.3.0'
  - '@tuwaio/siwx-server@0.3.0'
  - '@tuwaio/siwx-solana@0.3.0'
  - '@types/node@26.5.0'
  - '@typescript-eslint/eslint-plugin@8.70.0'
  - '@typescript-eslint/parser@8.70.0'
  - '@typescript-eslint/project-service@8.70.0'
  - '@typescript-eslint/scope-manager@8.70.0'
  - '@typescript-eslint/tsconfig-utils@8.70.0'
  - '@typescript-eslint/type-utils@8.70.0'
  - '@typescript-eslint/types@8.70.0'
  - '@typescript-eslint/typescript-estree@8.70.0'
  - '@typescript-eslint/utils@8.70.0'
  - '@typescript-eslint/visitor-keys@8.70.0'
  - typescript-eslint@8.70.0
